[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "instrumental-data-analyzer"
version = "0.3.3"
description = "A platform for analyzing instrumental data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "jupyterlab",
    "scipy",
    "scikit-learn",
    "impedance",
]

[project.optional-dependencies]
dev = ["pytest"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
